apiVersion: v1
kind: Pod
meatadata:
 name: empty-dir-pod
spec:
  conmtainers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/nginx
    - name: almalinux
      image: almalinux
      volumeMounts:
        - name: nginx-logs
          mountPath: /mnt/nginx-logs
  volumes:
    - name: nginx-logs
      emptyDir:
        sizeLimit: 500Mi