apiVersion: v1
kind: Pod
metadata:
  name: config-map
  labels:
    app: config-Map 
    environment: dev
    puporse: Lerning
spec:
  containers:
   - name: nginx
     image: nginx
     envFrom:
      - configMapRef:
         name: app-config